### ISSUE TITLE
 Seeking Information on Heat Pump Thermal Storage

### ISSUE THREAD

**Issue by ZeyuanWANGchn** [Tang1001/MPC-in-heat-pump-#1]
Hello,

I am a researcher in the field of heat pump thermal storage, and I am highly interested in your work, especially the application of Model Predictive Control (MPC). I am currently conducting research in the same domain.

I would like to explore your code, but I find that there is insufficient information within the codebase to fully comprehend its functionality. Could you please provide any associated papers or references that could help me gain a better understanding of your work?

Furthermore, if it's convenient for you, I would be very interested in the possibility of collaborating on this subject.

Looking forward to your response.

Best regards,
Zeyuan Wang
Email: upcwzy@163.com

**Comment by Tang1001** [comment]
@ZeyuanWANGchn Hello Zeyuan,

Thank you for reaching out and expressing interest in my work on heat pump thermal storage using Model Predictive Control (MPC). Sorry for the delay in my response.

This project is a collaboration with a company, and due to the nature of this partnership, we are restricted in the amount of information we can share at this time. However, once our research is published, I would be more than happy to share the findings with you if you are still interested.

I hope we can explore potential collaboration opportunities in the future. Wishing you all the best in your research endeavors.

Best regards,
Tony

**Comment by ZeyuanWANGchn** [comment]
Dear Tony,

Thank you very much for your prompt response and for sharing the status of your project on heat pump thermal storage using Model Predictive Control. I completely understand the confidentiality requirements associated with your collaboration and appreciate your willingness to share the findings once they are published.

I remain very interested in your work and would be grateful to learn about the research outcomes when they become available. Furthermore, I am hopeful that there might be an opportunity for us to collaborate in the future. I believe our combined expertise could lead to innovative advancements in this field.

Please do not hesitate to reach out if you see any potential for collaboration or if I can support your work in any way.

Wishing you continued success in your project and looking forward to the possibility of working together.

Best regards,

Zeyuan




At 2024-04-01 23:18:43, "WH Tang" ***@***.***> wrote:

@ZeyuanWANGchn Hello Zeyuan,

Thank you for reaching out and expressing interest in my work on heat pump thermal storage using Model Predictive Control (MPC). Sorry for the delay in my response.

This project is a collaboration with a company, and due to the nature of this partnership, we are restricted in the amount of information we can share at this time. However, once our research is published, I would be more than happy to share the findings with you if you are still interested.

I hope we can explore potential collaboration opportunities in the future. Wishing you all the best in your research endeavors.

Best regards,
Tony

**Comment by Tang1001** [comment]
@ZeyuanWANGchn Hi Zeyuan,

Thank you for your understanding and interest in the project. I am also keen on the potential for future collaboration and will certainly keep you updated on our progress and findings. 

Looking forward to the possibility of working together!

Best wishes,
Tony
